package com.xmscltd.scms.base.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWeixin<M extends BaseWeixin<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "Weixin:add";
    public static final String ACTION_DELETE = "Weixin:delete";
    public static final String ACTION_UPDATE = "Weixin:update";



	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setWxid(java.lang.String wxid) {
		set("wxid", wxid);
	}
	
	public java.lang.String getWxid() {
		return getStr("wxid");
	}

	public void setWxname(java.lang.String wxname) {
		set("wxname", wxname);
	}
	
	public java.lang.String getWxname() {
		return getStr("wxname");
	}

	public void setWxtype(java.lang.String wxtype) {
		set("wxtype", wxtype);
	}
	
	public java.lang.String getWxtype() {
		return getStr("wxtype");
	}

	public void setWxtoken(java.lang.String wxtoken) {
		set("wxtoken", wxtoken);
	}
	
	public java.lang.String getWxtoken() {
		return getStr("wxtoken");
	}

	public void setWxappid(java.lang.String wxappid) {
		set("wxappid", wxappid);
	}
	
	public java.lang.String getWxappid() {
		return getStr("wxappid");
	}

	public void setWxappsecret(java.lang.String wxappsecret) {
		set("wxappsecret", wxappsecret);
	}
	
	public java.lang.String getWxappsecret() {
		return getStr("wxappsecret");
	}

	public void setWxqrUrl(java.lang.String wxqrUrl) {
		set("wxqr_url", wxqrUrl);
	}
	
	public java.lang.String getWxqrUrl() {
		return getStr("wxqr_url");
	}

	public void setWxheadingUrl(java.lang.String wxheadingUrl) {
		set("wxheading_url", wxheadingUrl);
	}
	
	public java.lang.String getWxheadingUrl() {
		return getStr("wxheading_url");
	}

	public void setWxmchid(java.lang.String wxmchid) {
		set("wxmchid", wxmchid);
	}
	
	public java.lang.String getWxmchid() {
		return getStr("wxmchid");
	}

	public void setWxpaykey(java.lang.String wxpaykey) {
		set("wxpaykey", wxpaykey);
	}
	
	public java.lang.String getWxpaykey() {
		return getStr("wxpaykey");
	}

	public void setWxoauthUrl(java.lang.String wxoauthUrl) {
		set("wxoauth_url", wxoauthUrl);
	}
	
	public java.lang.String getWxoauthUrl() {
		return getStr("wxoauth_url");
	}

	public void setEncodingAesKey(java.lang.String encodingAesKey) {
		set("encodingAesKey", encodingAesKey);
	}
	
	public java.lang.String getEncodingAesKey() {
		return getStr("encodingAesKey");
	}

	public void setMessageEncrypt(java.lang.Boolean messageEncrypt) {
		set("messageEncrypt", messageEncrypt);
	}
	
	public java.lang.Boolean getMessageEncrypt() {
		return get("messageEncrypt");
	}

}
