package com.xmscltd.scms.base.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWXMpUser<M extends BaseWXMpUser<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "WxmpUser:add";
    public static final String ACTION_DELETE = "WxmpUser:delete";
    public static final String ACTION_UPDATE = "WxmpUser:update";


	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setMpid(java.lang.String mpid) {
		set("mpid", mpid);
	}
	
	public java.lang.String getMpid() {
		return getStr("mpid");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}
	
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public void setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
	}
	
	public java.lang.String getUnionid() {
		return getStr("unionid");
	}

}
