package com.xmscltd.scms.base.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "User:add";
    public static final String ACTION_DELETE = "User:delete";
    public static final String ACTION_UPDATE = "User:update";


	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setFullname(java.lang.String fullname) {
		set("fullname", fullname);
	}
	
	public java.lang.String getFullname() {
		return getStr("fullname");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setPwd(java.lang.String pwd) {
		set("pwd", pwd);
	}
	
	public java.lang.String getPwd() {
		return getStr("pwd");
	}

	public void setSalt2(java.lang.String salt2) {
		set("salt2", salt2);
	}
	
	public java.lang.String getSalt2() {
		return getStr("salt2");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public void setTelphone(java.lang.String telphone) {
		set("telphone", telphone);
	}
	
	public java.lang.String getTelphone() {
		return getStr("telphone");
	}

	public void setOnlineStatus(java.lang.String onlineStatus) {
		set("onlineStatus", onlineStatus);
	}
	
	public java.lang.String getOnlineStatus() {
		return getStr("onlineStatus");
	}

	public void setCompanyid(java.lang.String companyid) {
		set("companyid", companyid);
	}
	
	public java.lang.String getCompanyid() {
		return getStr("companyid");
	}

	public void setDepartmentid(java.lang.String departmentid) {
		set("departmentid", departmentid);
	}
	
	public java.lang.String getDepartmentid() {
		return getStr("departmentid");
	}

	public void setPosition(java.lang.String position) {
		set("position", position);
	}
	
	public java.lang.String getPosition() {
		return getStr("position");
	}

	public void setCredentialType(java.lang.Integer credentialType) {
		set("credentialType", credentialType);
	}
	
	public java.lang.Integer getCredentialType() {
		return getInt("credentialType");
	}

	public void setCredentialNum(java.lang.String credentialNum) {
		set("credentialNum", credentialNum);
	}
	
	public java.lang.String getCredentialNum() {
		return getStr("credentialNum");
	}

	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}
	
	public java.lang.Integer getGender() {
		return getInt("gender");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}
	
	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setLastUpdAcct(java.lang.String lastUpdAcct) {
		set("lastUpdAcct", lastUpdAcct);
	}
	
	public java.lang.String getLastUpdAcct() {
		return getStr("lastUpdAcct");
	}

	public void setLastUpdTime(java.util.Date lastUpdTime) {
		set("lastUpdTime", lastUpdTime);
	}
	
	public java.util.Date getLastUpdTime() {
		return get("lastUpdTime");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	public java.lang.String getNote() {
		return getStr("note");
	}

	public void setVersion(java.lang.String version) {
		set("version", version);
	}
	
	public java.lang.String getVersion() {
		return getStr("version");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

}
