package com.xmscltd.scms.base.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsg<M extends BaseMsg<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "Msg:add";
    public static final String ACTION_DELETE = "Msg:delete";
    public static final String ACTION_UPDATE = "Msg:update";



	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setSender(java.lang.String sender) {
		set("sender", sender);
	}
	
	public java.lang.String getSender() {
		return getStr("sender");
	}

	public void setReceiver(java.lang.String receiver) {
		set("receiver", receiver);
	}
	
	public java.lang.String getReceiver() {
		return getStr("receiver");
	}

	public void setContext(byte[] context) {
		set("context", context);
	}
	
	public byte[] getContext() {
		return get("context");
	}

	public void setSendtime(java.util.Date sendtime) {
		set("sendtime", sendtime);
	}
	
	public java.util.Date getSendtime() {
		return get("sendtime");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setIsread(java.lang.Boolean isread) {
		set("isread", isread);
	}
	
	public java.lang.Boolean getIsread() {
		return get("isread");
	}

}
