package com.xmscltd.scms.base.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "Role:add";
    public static final String ACTION_DELETE = "Role:delete";
    public static final String ACTION_UPDATE = "Role:update";



	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setRelotype(java.lang.String relotype) {
		set("relotype", relotype);
	}
	
	public java.lang.String getRelotype() {
		return getStr("relotype");
	}

	public void setDes(java.lang.String des) {
		set("des", des);
	}
	
	public java.lang.String getDes() {
		return getStr("des");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setLastUpdAcct(java.lang.String lastUpdAcct) {
		set("lastUpdAcct", lastUpdAcct);
	}
	
	public java.lang.String getLastUpdAcct() {
		return getStr("lastUpdAcct");
	}

	public void setLastUpdTime(java.util.Date lastUpdTime) {
		set("lastUpdTime", lastUpdTime);
	}
	
	public java.util.Date getLastUpdTime() {
		return get("lastUpdTime");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	public java.lang.String getNote() {
		return getStr("note");
	}

	public void setIconcls(java.lang.String iconcls) {
		set("iconcls", iconcls);
	}
	
	public java.lang.String getIconcls() {
		return getStr("iconcls");
	}

	public void setSeq(java.lang.Long seq) {
		set("seq", seq);
	}
	
	public java.lang.Long getSeq() {
		return getLong("seq");
	}

}
