package com.xmscltd.scms.base.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWXMaUser<M extends BaseWXMaUser<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "WxmaUser:add";
    public static final String ACTION_DELETE = "WxmaUser:delete";
    public static final String ACTION_UPDATE = "WxmaUser:update";


	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setMaid(java.lang.String maid) {
		set("maid", maid);
	}
	
	public java.lang.String getMaid() {
		return getStr("maid");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}
	
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public void setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
	}
	
	public java.lang.String getUnionid() {
		return getStr("unionid");
	}

	public void setIsfollow(java.lang.Boolean isfollow) {
		set("isfollow", isfollow);
	}

	public java.lang.Boolean getIsfollow() {
		return get("isfollow");
	}

}
