package com.xmscltd.scms.base.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuartz<M extends BaseQuartz<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "Quartz:add";
    public static final String ACTION_DELETE = "Quartz:delete";
    public static final String ACTION_UPDATE = "Quartz:update";



	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setJobType(java.lang.String jobType) {
		set("jobType", jobType);
	}
	
	public java.lang.String getJobType() {
		return getStr("jobType");
	}

	public void setJobName(java.lang.String jobName) {
		set("jobName", jobName);
	}
	
	public java.lang.String getJobName() {
		return getStr("jobName");
	}

	public void setJobGroup(java.lang.String jobGroup) {
		set("jobGroup", jobGroup);
	}
	
	public java.lang.String getJobGroup() {
		return getStr("jobGroup");
	}

	public void setTriggerName(java.lang.String triggerName) {
		set("triggerName", triggerName);
	}
	
	public java.lang.String getTriggerName() {
		return getStr("triggerName");
	}

	public void setTriggerGroupName(java.lang.String triggerGroupName) {
		set("triggerGroupName", triggerGroupName);
	}
	
	public java.lang.String getTriggerGroupName() {
		return getStr("triggerGroupName");
	}

	public void setJobClass(java.lang.String jobClass) {
		set("jobClass", jobClass);
	}
	
	public java.lang.String getJobClass() {
		return getStr("jobClass");
	}

	public void setCronExpr(java.lang.String cronExpr) {
		set("cronExpr", cronExpr);
	}
	
	public java.lang.String getCronExpr() {
		return getStr("cronExpr");
	}

	public void setPreviousFireTime(java.util.Date previousFireTime) {
		set("previousFireTime", previousFireTime);
	}
	
	public java.util.Date getPreviousFireTime() {
		return get("previousFireTime");
	}

	public void setNextFireTime(java.util.Date nextFireTime) {
		set("nextFireTime", nextFireTime);
	}
	
	public java.util.Date getNextFireTime() {
		return get("nextFireTime");
	}

	public void setJobStatus(java.lang.String jobStatus) {
		set("jobStatus", jobStatus);
	}
	
	public java.lang.String getJobStatus() {
		return getStr("jobStatus");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setLastUpdTime(java.util.Date lastUpdTime) {
		set("lastUpdTime", lastUpdTime);
	}
	
	public java.util.Date getLastUpdTime() {
		return get("lastUpdTime");
	}

	public void setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
	}
	
	public java.util.Date getStartTime() {
		return get("startTime");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}
	
	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public void setJobMemo(java.lang.String jobMemo) {
		set("jobMemo", jobMemo);
	}
	
	public java.lang.String getJobMemo() {
		return getStr("jobMemo");
	}

	public void setJobMethod(java.lang.String jobMethod) {
		set("jobMethod", jobMethod);
	}
	
	public java.lang.String getJobMethod() {
		return getStr("jobMethod");
	}

	public void setIntervalInMilliseconds(java.lang.Long intervalInMilliseconds) {
		set("intervalInMilliseconds", intervalInMilliseconds);
	}
	
	public java.lang.Long getIntervalInMilliseconds() {
		return getLong("intervalInMilliseconds");
	}

	public void setIntervalInSeconds(java.lang.Integer intervalInSeconds) {
		set("intervalInSeconds", intervalInSeconds);
	}
	
	public java.lang.Integer getIntervalInSeconds() {
		return getInt("intervalInSeconds");
	}

	public void setIntervalInMinutes(java.lang.Integer intervalInMinutes) {
		set("intervalInMinutes", intervalInMinutes);
	}
	
	public java.lang.Integer getIntervalInMinutes() {
		return getInt("intervalInMinutes");
	}

	public void setIntervalInHours(java.lang.Integer intervalInHours) {
		set("intervalInHours", intervalInHours);
	}
	
	public java.lang.Integer getIntervalInHours() {
		return getInt("intervalInHours");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}
	
	public java.lang.Integer getCount() {
		return getInt("count");
	}

	public void setJobObject(java.lang.String jobObject) {
		set("jobObject", jobObject);
	}
	
	public java.lang.String getJobObject() {
		return getStr("jobObject");
	}

	public void setJobDataMap(byte[] jobDataMap) {
		set("jobDataMap", jobDataMap);
	}
	
	public byte[] getJobDataMap() {
		return get("jobDataMap");
	}

}
