package com.xmscltd.scms.base.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserRes<M extends BaseUserRes<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "UserRes:add";
    public static final String ACTION_DELETE = "UserRes:delete";
    public static final String ACTION_UPDATE = "UserRes:update";



	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setResId(java.lang.Long resId) {
		set("res_id", resId);
	}
	
	public java.lang.Long getResId() {
		return getLong("res_id");
	}

}
