package com.xmscltd.scms.base.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDepartment<M extends BaseDepartment<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "Department:add";
    public static final String ACTION_DELETE = "Department:delete";
    public static final String ACTION_UPDATE = "Department:update";



	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setParentid(java.lang.Integer parentid) {
		set("parentid", parentid);
	}
	
	public java.lang.Integer getParentid() {
		return getInt("parentid");
	}

	public void setParentname(java.lang.String parentname) {
		set("parentname", parentname);
	}
	
	public java.lang.String getParentname() {
		return getStr("parentname");
	}

	public void setCreater(java.lang.String creater) {
		set("creater", creater);
	}
	
	public java.lang.String getCreater() {
		return getStr("creater");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setUpdater(java.lang.String updater) {
		set("updater", updater);
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}

	public void setLastupdatetime(java.util.Date lastupdatetime) {
		set("lastupdatetime", lastupdatetime);
	}
	
	public java.util.Date getLastupdatetime() {
		return get("lastupdatetime");
	}

	public void setEnable(java.lang.String enable) {
		set("enable", enable);
	}
	
	public java.lang.String getEnable() {
		return getStr("enable");
	}

	public void setLEAF(java.lang.String LEAF) {
		set("LEAF", LEAF);
	}
	
	public java.lang.String getLEAF() {
		return getStr("LEAF");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}
	
	public java.lang.String getDesc() {
		return getStr("desc");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}

	public java.lang.String getIcon() {
		return getStr("icon");
	}

	public void setLongnumber(java.lang.String longnumber) {
		set("longnumber", longnumber);
	}

	public java.lang.String getLongnumber() {
		return getStr("longnumber");
	}
}
