package com.xmscltd.scms.base.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWXQyUser<M extends BaseWXQyUser<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "WxqyUser:add";
    public static final String ACTION_DELETE = "WxqyUser:delete";
    public static final String ACTION_UPDATE = "WxqyUser:update";



	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setQyid(java.lang.String qyid) {
		set("qyid", qyid);
	}
	
	public java.lang.String getQyid() {
		return getStr("qyid");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}
	
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public void setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
	}
	
	public java.lang.String getUnionid() {
		return getStr("unionid");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

}
