package com.xmscltd.scms.base.model;

import io.jboot.db.annotation.Table;
import com.xmscltd.scms.base.model.base.BaseDepartment;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_department", primaryKey = "id")
public class Department extends BaseDepartment<Department> {
	
}
