package com.xmscltd.scms.base.model;

import io.jboot.db.annotation.Table;
import com.xmscltd.scms.base.model.base.BaseLog;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_log", primaryKey = "id")
public class Log extends BaseLog<Log> {
	
}
