package com.xmscltd.scms.base.model;

import io.jboot.db.annotation.Table;
import com.xmscltd.scms.base.model.base.BaseMsg;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_msg", primaryKey = "id")
public class Msg extends BaseMsg<Msg> {
	
}
