package com.xmscltd.scms.base.model;

import com.xmscltd.scms.base.model.base.BaseQuartz;

import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_quartz", primaryKey = "id")
public class Quartz extends BaseQuartz<Quartz> {


}
