package com.xmscltd.scms.base.model;

import io.jboot.db.annotation.Table;
import com.xmscltd.scms.base.model.base.BaseRes;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_res", primaryKey = "id")
public class Res extends BaseRes<Res> {
	
}
