package com.xmscltd.scms.base.model;

import io.jboot.db.annotation.Table;
import com.xmscltd.scms.base.model.base.BaseRoleRes;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_role_res", primaryKey = "id")
public class RoleRes extends BaseRoleRes<RoleRes> {
	
}
