package com.xmscltd.scms.base.model;

import io.jboot.db.annotation.Table;
import com.xmscltd.scms.base.model.base.BaseRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_role", primaryKey = "id")
public class Role extends BaseRole<Role> {
	
}
