package com.xmscltd.scms.base.model;

import io.jboot.db.annotation.Table;
import com.xmscltd.scms.base.model.base.BaseUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_user", primaryKey = "id")
public class User extends BaseUser<User> {
	
}
