package com.xmscltd.scms.base.model;

import io.jboot.db.annotation.Table;
import com.xmscltd.scms.base.model.base.BaseUserRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_user_role", primaryKey = "id")
public class UserRole extends BaseUserRole<UserRole> {
	
}
