package com.xmscltd.scms.base.model;

import io.jboot.db.annotation.Table;
import com.xmscltd.scms.base.model.base.BaseUserRes;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_user_res", primaryKey = "id")
public class UserRes extends BaseUserRes<UserRes> {
	
}
