package com.xmscltd.scms.base.model;

import io.jboot.db.annotation.Table;
import com.xmscltd.scms.base.model.base.BaseWeixin;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_weixin", primaryKey = "id")
public class Weixin extends BaseWeixin<Weixin> {
	
}
