package com.xmscltd.scms.base.model;

import com.xmscltd.scms.base.model.base.BaseWXMaUser;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_wxma_user", primaryKey = "id")
public class WXMaUser extends BaseWXMaUser<WXMaUser> {
	
}
