package com.xmscltd.scms.base.model;

import com.xmscltd.scms.base.model.base.BaseWXMpUser;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_wxmp_user", primaryKey = "id")
public class WXMpUser extends BaseWXMpUser<WXMpUser> {
	
}
