package com.xmscltd.scms.base.model;

import com.xmscltd.scms.base.model.base.BaseWXQyUser;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_wxqy_user", primaryKey = "id")
public class WXQyUser extends BaseWXQyUser<WXQyUser> {
	
}
