package com.xmscltd.scms.base.model;

import io.jboot.db.annotation.Table;
import com.xmscltd.scms.base.model.base.BaseWXUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_wxuser", primaryKey = "id")
public class WXUser extends BaseWXUser<WXUser> {
	
}
